# Duplicate from one of the existing configs and change the name to ....+nightly + vllm image
# see the existing LLMInferenceServiceConfig with `oc get LLMInferenceServiceConfig -A`
apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  annotations:
    openshift.io/description: nightly vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig for LLMInferenceService.
    openshift.io/display-name: nightly vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig
    serving.kserve.io/well-known-config: 'true'
    internal.config.kubernetes.io/previousNamespaces: opendatahub
    internal.config.kubernetes.io/previousKinds: LLMInferenceServiceConfig
    platform.opendatahub.io/instance.generation: '2'
    internal.config.kubernetes.io/previousNames: kserve-config-llm-template-nvidia-cuda
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: v3-4-3-kserve-config-llm-template-nvidia-cuda-nightly
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: kserve
    app.opendatahub.io/kserve: 'true'
    opendatahub.io/config-type: accelerator
    platform.opendatahub.io/part-of: kserve
spec:
  template:
    containers:
      - image: 'vllm/vllm-openai:nightly'
        name: main
---
# Autogenerated config if deployed via the UI
apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: LLMInferenceServiceConfig
    internal.config.kubernetes.io/previousNames: kserve-config-llm-template-nvidia-cuda
    internal.config.kubernetes.io/previousNamespaces: opendatahub
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-name: v3-4-3-kserve-config-llm-template-nvidia-cuda-nightly
    openshift.io/description: nightly vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig
      for LLMInferenceService.
    openshift.io/display-name: nightly vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig
    platform.opendatahub.io/instance.generation: "2"
    platform.opendatahub.io/instance.name: default-kserve
    platform.opendatahub.io/instance.uid: 112b72af-bd97-48ab-bc72-1d5dd691045f
    platform.opendatahub.io/type: OpenShift AI Self-Managed
    platform.opendatahub.io/version: 3.4.3
    serving.kserve.io/well-known-config: "true"
  generation: 1
  name: muse-glimmer-llmisvc-nightly
  namespace: swongpai-vllm
spec:
  model:
    uri: ""
  template:
    containers:
    - image: vllm/vllm-openai:nightly
      name: main
      resources: {}